name: 🖳🇨🇭 Server Pinger 🔒🔑
#DEPENDS: SF_SSH_HOSTS (main script) as Repo Secret
on:
  workflow_dispatch: # Whenever manually run from actions-tab
  schedule:
    - cron: "15 23 * * *" #( 11:15 PM UTC --> 05:00 AM Morning )
#------------------------------------------------------------------------------------#  
jobs:
  Ping:
    runs-on: ubuntu-latest
    #timeout-minutes: 05
    permissions:
      contents: write
    steps:
    
      - name: Install Coreutils
        run: |
          # Presets
          set -x ; set +e
          #--------------#
          sudo apt update -y
          sudo apt install coreutils curl dos2unix jq moreutils wget -y
          # Again just because
          sudo apt install coreutils curl dos2unix jq moreutils wget -y
        continue-on-error: true

      - name: Install eget
        run: |
          # Presets
          set -x ; set +e
          #--------------#
          # eget for bins
          sudo wget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/eget" -O "/usr/local/bin/eget"
          sudo chmod +xwr "/usr/local/bin/eget"
        continue-on-error: false
     
      - name: 🖳🇨🇭 Ping SF Hosts 🔒🔑
        run: |
          # Presets
          set +x ; set +e
          #--------------#
          #GetScript
          echo '${{ secrets.SF_SSH_HOSTS }}' > "/tmp/sf.sh"
          #dos2unix && chmod
          dos2unix "/tmp/sf.sh" ; chmod +xwr "/tmp/sf.sh"
          #Run
          bash "/tmp/sf.sh" 2>/dev/null
          #bash "/tmp/sf.sh" >/dev/null 2>&1
        continue-on-error: true
