name: 🖳🇨🇭 Server Pinger 🔒🔑
on:
  workflow_dispatch: # Whenever manually run from actions-tab
  #schedule:
  #  - cron: "*/35 * * * *" #Every 35 Mins
#------------------------------------------------------------------------------------#  
jobs:
  Ping:
    runs-on: ubuntu-latest
    #timeout-minutes: 05
    permissions:
      contents: write
      
    steps:        
      - name: 🖳🇨🇭 Ping SF Hosts 🔒🔑
        run: |
          # Presets
          set -x ; set +e
          #--------------#
          #GetScript
          echo '${{ secrets.SF_SSH_HOSTS }}' > "/tmp/sf.sh"
          #dos2unix && chmod
          dos2unix "/tmp/sf.sh" ; chmod +xwr "/tmp/sf.sh"
          #Run
          bash "/tmp/sf.sh" 2>/dev/null
          #bash "/tmp/sf.sh" >/dev/null 2>&1
        continue-on-error: true
